header:
  version: 9

distro: poky

defaults:
  repos:
    refspec: master

repos:
  meta-trustedsubstrate:
    layers:
        meta-trustedsubstrate:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    refspec: 0539b563c6f41fef383429a13c28bf918231d404
    layers:
      meta:
      meta-poky:
    patches:
      p1:
        repo : poky
        path : ../../patches/0001-wic-add-UEFI-kernel-as-UEFI-stub.patch
      p2:
        repo : poky
        path : ../../patches/0002-wic-bootimg-efi-implement-include-path.patch
      p3:
        repo : poky
        path : ../../patches/0003-uninative-Upgrade-to-3.6-with-gcc-12-support.patch
  meta-arm:
    path: layers/meta-arm
    url: git://git.yoctoproject.org/meta-arm
    refspec: 3ee7d019898854f776f95ed31f4b7ea8c8a73dfe
    layers:
      meta-arm:
      meta-arm-bsp:
      meta-arm-toolchain:

env:
  BB_LOGCONFIG: ""
  TOOLCHAIN_DIR: ""

local_conf_header:
  base: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    LICENSE_FLAGS_ACCEPTED += "armcompiler Arm-FVP-EULA"
    PACKAGECONFIG:remove:pn-qemu-system-native = "gtk+ sdl"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    BB_NUMBER_THREADS = "16"
    PARALLEL_MAKE = "-j16"
    INHERIT += "rm_work"
    PACKAGECONFIG:append:pn-perf = " coresight"
    BB_ENV_PASSTHROUGH_ADDITIONS = "UEFI_CERT_FILE"
    UEFI_CERT_FILE = "${TOPDIR}/../meta-trustedsubstrate/uefi-certificates/uefi_certs.tgz"
    INHERIT += "buildhistory"
    BUILDHISTORY_COMMIT = "1"
  noptest: |
    DISTRO_FEATURES:remove = "ptest"

machine: unset

target:
  - ts-firmware
