header:
  version: 9

distro: poky

defaults:
  repos:
    refspec: master

repos:
  meta-trustedsubstrate:
    layers:
        meta-trustedsubstrate:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    refspec: e81e703fb6fd028f5d01488a62dcfacbda16aa9e
    layers:
      meta:
      meta-poky:
  meta-arm:
    path: layers/meta-arm
    url: git://git.yoctoproject.org/meta-arm
    refspec: 0a5eba13d81f5c5722a13b816193ebf93c0fd198
    layers:
      meta-arm:
      meta-arm-bsp:
      meta-arm-toolchain:

env:
  BB_LOGCONFIG: ""
  TOOLCHAIN_DIR: ""

local_conf_header:
  base: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    LICENSE_FLAGS_ACCEPTED += "armcompiler Arm-FVP-EULA"
    PACKAGECONFIG:remove:pn-qemu-system-native = "gtk+ sdl"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    BB_NUMBER_THREADS = "16"
    PARALLEL_MAKE = "-j16"
    INHERIT += "rm_work"
    PACKAGECONFIG:append:pn-perf = " coresight"
    BB_ENV_PASSTHROUGH_ADDITIONS = "UEFI_CERT_FILE"
    UEFI_CERT_FILE = "${TOPDIR}/../meta-trustedsubstrate/uefi-certificates/uefi_certs.tgz"
    BB_ENV_PASSTHROUGH_ADDITIONS = "UEFI_CAPSULE_CERT_FILE"
    UEFI_CAPSULE_CERT_FILE = "${TOPDIR}/../meta-trustedsubstrate/uefi-certificates/capsule_certs.tgz"
    INHERIT += "buildhistory"
    BUILDHISTORY_COMMIT = "1"
  noptest: |
    DISTRO_FEATURES:remove = "ptest"

machine: unset

target:
  - ts-firmware
